server:
  port: 8084
  context-path: /test

spring:
    datasource:
        name: test
        url: jdbc:mysql://127.0.0.1:3306/test
        username: root
        password: 123456
        # 使用druid数据源
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        filters: stat
        maxActive: 20
        initialSize: 1
        maxWait: 60000
        minIdle: 1
        timeBetweenEvictionRunsMillis: 60000
        minEvictableIdleTimeMillis: 300000
        validationQuery: select 'x'
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        poolPreparedStatements: true
        maxOpenPreparedStatements: 20
    redis:
        host: 127.0.0.1
        port: 6379
        timeout: 0
        database: 0
        pool:
          max-active: 8
          max-wait: -1
          max-idle: 8
          min-idle: 0
    mongodb:
          uri: mongodb://localhost:27017/test
    rocketmq:
      name-server: localhost:9876
      producer-group-name: spring-boot-test-producer-group

    elasticsearch:
                #cluster-name: #默认为elasticsearch
                #cluster-nodes: 127.0.0.1: #配置es节点信息，逗号分隔，如果没有指定，则启动ClientNode
                properties:
                    path:
                      logs: ./elasticsearch/log #elasticsearch日志存储目录
                      data: ./elasticsearch/data #elasticsearch数据存储目录
mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.model

#pagehelper
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql




